---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villain-microservice
  labels:
    app: villain-microservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: villain-microservice
  template:
    metadata:
      labels:
        app: villain-microservice
    spec:
      containers:
      - name: villain-microservice
        image: workshop/villain-microservice:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: QUARKUS_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: villain-config
                key: database
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: villain-database-secret
                key: username
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: villain-database-secret
                key: password
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
