---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fight-microservice
  labels:
    app: fight-microservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fight-microservice
  template:
    metadata:
      labels:
        app: fight-microservice
    spec:
      containers:
      - name: fight-microservice
        image: workshop/fight-microservice:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
